### ISSUE TITLE
Prefix shared code

### ISSUE THREAD

**Issue by gregtatum** [TatumCreative/mdn-webgl#7]
I'm wondering if I should collect all of the shared functions on an object. I think it's confusing when you come across a randomly defined function and you don't know where it came from.

  var translate = MDN.translationMatrix(0,-1,0);

I'm not sure what that object prefix should be called.

**Comment by nickdesaulniers** [comment]
> I think it's confusing when you come across a randomly defined function and you don't know where it came from.

Agree!

That is a really great idea!

**Comment by gregtatum** [comment]
Yup, this really helps in reading the code now that I've done it on the lighting models.
